apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.4.3
    helm:
      values: |
        repoServer:
          env:
            - name: SSL_CERT_DIR
              value: "/app/config/tls/"
        server:
          env:
            - name: SSL_CERT_DIR
              value: "/app/config/tls/"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
